name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  transpire-ci:
    uses: ocf/transpire-ci/.github/workflows/trigger.yml@master
    with:
      module_name: grafana
    secrets:
      TRANSPIRE_CI_PAT: ${{ secrets.TRANSPIRE_CI_PAT }}
